# ArgoCD Helm Chart Values for GitOps, node-specific deployment, and declarative management

# Global configuration
# (No global image override, use chart defaults)

server:
  nodeSelector:
    type: "dependent_services"
  tolerations: []
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443
  ingress:
    enabled: false
  extraArgs:
    - --insecure
  # Optionally, set resources/limits here

controller:
  nodeSelector:
    type: "dependent_services"
  tolerations: []

repoServer:
  nodeSelector:
    type: "dependent_services"
  tolerations: []

redis:
  nodeSelector:
    type: "dependent_services"
  tolerations: []

applicationSet:
  enabled: true
  nodeSelector:
    type: "dependent_services"
  tolerations: []

notifications:
  enabled: true
  nodeSelector:
    type: "dependent_services"
  tolerations: []

dex:
  enabled: false

configs:
  params:
    server.insecure: true
    accounts.admin: apiKey,login
    application.instanceLabelKey: argocd.argoproj.io/instance
  cm:
    # Enable auto-sync by default for all apps (can be overridden per app)
    accounts.admin: apiKey,login
    # Optionally, set resource customizations, RBAC, etc.

rbac:
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    g, admin, role:admin
