# ArgoCD Helm Chart Values
# This file configures the ArgoCD installation with GitOps best practices

# Global configuration
global:
  image:
    tag: "v2.12.3"  # Pin to stable version
  
# ArgoCD Server Configuration
server:
  # Enable insecure mode for internal cluster access
  insecure: true
  
  # Node selector to deploy on dependent_services node
  nodeSelector:
    type: "dependent_services"
  
  # Tolerations for dependent_services node if needed
  tolerations: []
  
  # Service configuration
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443
  
  # Ingress configuration (disabled for NodePort setup)
  ingress:
    enabled: false
  
  # Additional server arguments
  extraArgs:
    - --insecure

# Repository Server Configuration
repoServer:
  nodeSelector:
    type: "dependent_services"
  
  tolerations: []

# Application Controller Configuration
controller:
  nodeSelector:
    type: "dependent_services"
  
  tolerations: []
  
  # Controller configuration
  config:
    # Increase sync timeout for large applications
    timeout.reconciliation: 300s
    timeout.hard.reconciliation: 0s

# Redis Configuration
redis:
  nodeSelector:
    type: "dependent_services"
  
  tolerations: []

# Dex (OIDC) Configuration - disabled for simplicity
dex:
  enabled: false

# Notifications controller
notifications:
  enabled: true
  nodeSelector:
    type: "dependent_services"
  tolerations: []

# ApplicationSet controller
applicationSet:
  enabled: true
  nodeSelector:
    type: "dependent_services"
  tolerations: []

# Additional ArgoCD configuration
configs:
  # Configure default project settings
  params:
    # Enable local users (admin)
    accounts.admin: apiKey, login
    
    # Server configuration
    server.insecure: true
    server.rootpath: /
    
    # Repository server configuration
    reposerver.parallelism.limit: 10
    
    # Application controller configuration
    application.instanceLabelKey: argocd.argoproj.io/instance

# RBAC Configuration
rbac:
  # Configure RBAC policies
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    g, admin, role:admin
