---
# PostgreSQL Service for internal cluster communication
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: database
  labels:
    app: postgres
    tier: data
spec:
  type: ClusterIP  # Internal only
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
---
# PostgreSQL ConfigMap for initialization SQL
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: database
data:
  init.sql: |
    -- Create students table if not exists
    CREATE TABLE IF NOT EXISTS students (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        age INTEGER CHECK (age > 0),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Insert sample data
    INSERT INTO students (name, email, age) VALUES 
    ('Alice Johnson', 'alice.johnson@university.edu', 20),
    ('Bob Smith', 'bob.smith@university.edu', 22),
    ('Charlie Brown', 'charlie.brown@university.edu', 19),
    ('Diana Prince', 'diana.prince@university.edu', 21),
    ('Edward Wilson', 'edward.wilson@university.edu', 23)
    ON CONFLICT (email) DO NOTHING;

    -- Create index for better performance
    CREATE INDEX IF NOT EXISTS idx_students_email ON students(email);
    CREATE INDEX IF NOT EXISTS idx_students_age ON students(age);
