{{- if .Values.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "student-api-stack.labels" . | nindent 4 }}
    type: application
    tier: app
{{- end }}
