{{- if .Values.studentApi.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "student-api-stack.fullname" . }}-api
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "student-api-stack.studentApi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.studentApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "student-api-stack.studentApi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "student-api-stack.studentApi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: student-api
        image: "{{ .Values.studentApi.image.repository }}:{{ .Values.studentApi.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.studentApi.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.studentApi.service.targetPort }}
          protocol: TCP
        env:
        - name: FLASK_ENV
          value: {{ .Values.studentApi.env.FLASK_ENV | quote }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "student-api-stack.fullname" . }}-api-secret
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "student-api-stack.fullname" . }}-api-secret
              key: redis-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "student-api-stack.fullname" . }}-api-secret             
              key: flask-secret-key
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: {{ .Values.studentApi.service.targetPort | quote }}
        resources:
          {{- toYaml .Values.studentApi.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "student-api-stack.fullname" . }}-api
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "student-api-stack.studentApi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.studentApi.service.type }}
  ports:
    - port: {{ .Values.studentApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "student-api-stack.studentApi.selectorLabels" . | nindent 4 }}
{{- end }}
