# ============================================================================
# values.yaml for "observability-stack" Helm umbrella chart
# Minimal PLG (Promtail, Loki, Grafana) + Prometheus setup for **Minikube**
# • All components run inside the cluster
# • No external object‑storage or persistence
# • Promtail scrapes only the `student-api` namespace
# ============================================================================

# ----------------------------------------------------------------------------
# GLOBAL
# ----------------------------------------------------------------------------
global:
  storageClass: "standard"  # default Minikube StorageClass

# ----------------------------------------------------------------------------
# LOKI  – single‑binary, filesystem storage
# ----------------------------------------------------------------------------
loki:
  enabled: true
  deploymentMode: SingleBinary                # 1‑pod Loki

  # ----- Loki run‑time configuration (matches loki-config.yaml in chart) -----
  loki:
    auth_enabled: false

    commonConfig:
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
        instance_addr: 127.0.0.1            # OK for single‑binary

    storage:
      type: filesystem
      filesystem:
        directory: /tmp/loki/chunks          # inside container

    schemaConfig:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    limits_config:
      retention_period: 1h                 # short retention for testing
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

  # ----- Pod‑level overrides -----
  singleBinary:
    persistence:
      enabled: false                         # no PVC on Minikube
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 512Mi
    extraArgs:
      - -validation.allow-structured-metadata=false
    readinessProbe:
      httpGet:
        path: /ready
        port: http-metrics
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

  # ----- Disable ALL distributed components to silence Helm validation -----
  backend:            { replicas: 0 }
  read:               { replicas: 0 }
  write:              { replicas: 0 }
  ingester:           { replicas: 0 }
  querier:            { replicas: 0 }
  queryFrontend:      { replicas: 0 }
  queryScheduler:     { replicas: 0 }
  distributor:        { replicas: 0 }
  compactor:          { replicas: 0 }
  indexGateway:       { replicas: 0 }
  memcached:          { enabled: false }
  memcachedChunks:    { enabled: false }
  memcachedFrontend:  { enabled: false }
  memcachedIndexQueries: { enabled: false }
  memcachedIndexWrites:  { enabled: false }
  chunksCache:        { enabled: false }
  resultsCache:       { enabled: false }

# ----------------------------------------------------------------------------
# PROMTAIL  – scrape only `student-api` namespace
# ----------------------------------------------------------------------------
promtail:
  enabled: true
  config:
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    clients:
      - url: http://observability-stack-loki:3100/loki/api/v1/push  # releaseName‑loki
        timeout: 10s
        backoff_config:
          min_period: 500ms
          max_period: 5m
          max_retries: 10
    positions:
      filename: /tmp/positions.yaml

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: student-api
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
            action: replace
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
            action: replace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
            action: replace
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
            action: replace

  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# ----------------------------------------------------------------------------
# GRAFANA  – expose via NodePort 32000
# ----------------------------------------------------------------------------
grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin123
  persistence:
    enabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://observability-stack-loki:3100
          access: proxy
          isDefault: true
  service:
    type: NodePort
    nodePort: 32000

# ----------------------------------------------------------------------------
# PROMETHEUS  – lightweight, no PVC
# ----------------------------------------------------------------------------
prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: false
    retention: "7d"
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: true

# ----------------------------------------------------------------------------
# Disable extra exporters for now
# ----------------------------------------------------------------------------
blackboxExporter:
  enabled: false
postgresExporter:
  enabled: false
