name: CI Pipeline

on:
  push:
    paths:
      - 'student-api/**' # Trigger only when changes are made in the 'student-api' directory
  workflow_dispatch: # Allow manual triggering of the pipeline

jobs:
  ci-pipeline:
    runs-on: self-hosted
    environment: demo
    steps:
      # Checkout the repository into a specific path
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: API_PROJECT

      # Debug the working directory
      - name: Debug Working Directory
        run: |
          echo "Current Directory: $(pwd)"
          echo "Working Directory: C:\Users\ayush_ihx9hgx\actions-runner\_work\API_PROJECT\API_PROJECT\student-api\student-api"
          ls -R C:\Users\ayush_ihx9hgx\actions-runner\_work\API_PROJECT\API_PROJECT\student-api\student-api
        shell: powershell

      # Build the API
      - name: Build API
        run: make build-api
        working-directory: C:\Users\ayush_ihx9hgx\actions-runner\_work\API_PROJECT\API_PROJECT\student-api\student-api

      # Run tests
      - name: Run Tests
        run: |
          $result = make test
          if ($LASTEXITCODE -eq 0) {
            echo "Tests passed."
          } else {
            echo "Tests failed."
            exit 1
          }
        shell: powershell
        working-directory: C:\Users\ayush_ihx9hgx\actions-runner\_work\API_PROJECT\API_PROJECT\student-api\student-api

      # Perform code linting
      - name: Code Linting
        run: make lint
        working-directory: C:\Users\ayush_ihx9hgx\actions-runner\_work\API_PROJECT\API_PROJECT\student-api\student-api

      # Docker login
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # Docker build and push
      - name: Docker Build and Push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/student-api:latest
        working-directory: C:\Users\ayush_ihx9hgx\actions-runner\_work\API_PROJECT\API_PROJECT\student-api\student-api