name: CI Pipeline

on:
  push:
    paths:
      - 'student-api/**' # Trigger only when changes are made in the 'student-api' directory
  workflow_dispatch: # Allow manual triggering of the pipeline

jobs:
  ci-pipeline:
    runs-on: self-hosted
    environment: demo
    steps:
      # Checkout the repository into a specific path
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: API_PROJECT

      # Set the working directory statically
      - name: Set Working Directory
        run: echo "WORKING_DIR=API_PROJECT/API_PROJECT/student-api" >> $env:GITHUB_ENV
        shell: pwsh

      # Debug the working directory
      - name: Debug Working Directory
        run: |
          echo "Current Directory: $(pwd)"
          echo "Working Directory: $WORKING_DIR"
          ls -R $WORKING_DIR
        shell: pwsh

      # Build the API
      - name: Build API
        run: make build-api
        working-directory: API_PROJECT/API_PROJECT/student-api

      # Run tests
      - name: Run Tests
        run: |
          if make test; then
            echo "Tests passed."
          else
            echo "Tests failed."
            exit 1
          fi
        working-directory: API_PROJECT/API_PROJECT/student-api

      # Perform code linting
      - name: Code Linting
        run: make lint
        working-directory: API_PROJECT/API_PROJECT/student-api

      # Docker login
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # Docker build and push
      - name: Docker Build and Push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/student-api:latest
        working-directory: API_PROJECT/API_PROJECT/student-api